name: Test workflow
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # Prevent duplicate builds on internal PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Compile library
        run: ./gradlew :centrifuge:jar

      - name: Run unit tests
        run: ./gradlew :centrifuge:test

  compileAndroidSample:
    runs-on: ubuntu-latest
    # Prevent duplicate builds on internal PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Compile Android Demo app
        run: ./gradlew :demo:assembleDebug

  compileJavaSample:
    runs-on: ubuntu-latest
    # Prevent duplicate builds on internal PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Compile Java Example app
        run: ./gradlew :example:assemble

  checkApiCompatibility:
    runs-on: ubuntu-latest
    # Prevent duplicate builds on internal PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Generate current API signatures
        run: ./gradlew :centrifuge:metalavaGenerateTempSignature

      - name: Calculate API diff
        run: git diff --no-index centrifuge/api.txt centrifuge/build/metalava/current.txt

# TODO: uncomment this when permisison to comment on PR is available
#      - uses: int128/diff-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          base: centrifuge/api.txt
#          head: centrifuge/build/metalava/current.txt
#          label: api-changed

      - name: Check API compatibility
        run: ./gradlew :centrifuge:metalavaCheckCompatibility